#include "cli_filter_lua.h"
cli_lua_option_t srun_opt_li[] = {
	{ "accel_bind_type", offsetof(struct srun_opt, accel_bind_type),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "alloc_nodelist", offsetof(struct srun_opt, alloc_nodelist),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "allocate", offsetof(struct srun_opt, allocate),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "argc", offsetof(struct srun_opt, argc), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "argv", offsetof(struct srun_opt, argv), cli_lua_stringarray, NULL,
		 "argc" },
	{ "bcast_file", offsetof(struct srun_opt, bcast_file),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "bcast_flag", offsetof(struct srun_opt, bcast_flag),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "burst_buffer", offsetof(struct srun_opt, burst_buffer),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "ckpt_dir", offsetof(struct srun_opt, ckpt_dir),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "ckpt_interval", offsetof(struct srun_opt, ckpt_interval),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ckpt_interval_str", offsetof(struct srun_opt, ckpt_interval_str),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "cmd_name", offsetof(struct srun_opt, cmd_name),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "compress", offsetof(struct srun_opt, compress),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "core_spec_set", offsetof(struct srun_opt, core_spec_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "cpu_bind", offsetof(struct srun_opt, cpu_bind),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "cpu_bind_type", offsetof(struct srun_opt, cpu_bind_type),
		 cli_lua_push_unsigned, cli_lua_set_unsigned, NULL },
	{ "cpu_bind_type_set", offsetof(struct srun_opt, cpu_bind_type_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "cwd_set", offsetof(struct srun_opt, cwd_set), cli_lua_push_boolean,
		 cli_lua_set_boolean, NULL },
	{ "debugger_test", offsetof(struct srun_opt, debugger_test),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "disable_status", offsetof(struct srun_opt, disable_status),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "efname", offsetof(struct srun_opt, efname), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "epilog", offsetof(struct srun_opt, epilog), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "exclusive", offsetof(struct srun_opt, exclusive),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "export_env", offsetof(struct srun_opt, export_env),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "hostfile", offsetof(struct srun_opt, hostfile),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "ifname", offsetof(struct srun_opt, ifname), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "job_name_set_cmd", offsetof(struct srun_opt, job_name_set_cmd),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "job_name_set_env", offsetof(struct srun_opt, job_name_set_env),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "kill_bad_exit", offsetof(struct srun_opt, kill_bad_exit),
		 cli_lua_push_int32_t, cli_lua_set_int32_t, NULL },
	{ "labelio", offsetof(struct srun_opt, labelio), cli_lua_push_boolean,
		 cli_lua_set_boolean, NULL },
	{ "launch_cmd", offsetof(struct srun_opt, launch_cmd),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "launcher_opts", offsetof(struct srun_opt, launcher_opts),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "max_exit_timeout", offsetof(struct srun_opt, max_exit_timeout),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "max_threads", offsetof(struct srun_opt, max_threads),
		 cli_lua_push_int32_t, cli_lua_set_int32_t, NULL },
	{ "max_wait", offsetof(struct srun_opt, max_wait), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "msg_timeout", offsetof(struct srun_opt, msg_timeout),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "multi_prog", offsetof(struct srun_opt, multi_prog),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "multi_prog_cmds", offsetof(struct srun_opt, multi_prog_cmds),
		 cli_lua_push_int32_t, cli_lua_set_int32_t, NULL },
	{ "network_set_env", offsetof(struct srun_opt, network_set_env),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "no_alloc", offsetof(struct srun_opt, no_alloc),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "nodes_set_env", offsetof(struct srun_opt, nodes_set_env),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "nodes_set_opt", offsetof(struct srun_opt, nodes_set_opt),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "noshell", offsetof(struct srun_opt, noshell), cli_lua_push_boolean,
		 cli_lua_set_boolean, NULL },
	{ "ofname", offsetof(struct srun_opt, ofname), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "open_mode", offsetof(struct srun_opt, open_mode),
		 cli_lua_push_uint8_t, cli_lua_set_uint8_t, NULL },
	{ "pack_group", offsetof(struct srun_opt, pack_group),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "pack_step_cnt", offsetof(struct srun_opt, pack_step_cnt),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "parallel_debug", offsetof(struct srun_opt, parallel_debug),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "preserve_env", offsetof(struct srun_opt, preserve_env),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "prolog", offsetof(struct srun_opt, prolog), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "propagate", offsetof(struct srun_opt, propagate),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "pty", offsetof(struct srun_opt, pty), cli_lua_push_boolean,
		 cli_lua_set_boolean, NULL },
	{ "quit_on_intr", offsetof(struct srun_opt, quit_on_intr),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "relative", offsetof(struct srun_opt, relative), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "relative_set", offsetof(struct srun_opt, relative_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "restart_dir", offsetof(struct srun_opt, restart_dir),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "resv_port_cnt", offsetof(struct srun_opt, resv_port_cnt),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "slurmd_debug", offsetof(struct srun_opt, slurmd_debug),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "task_epilog", offsetof(struct srun_opt, task_epilog),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "task_prolog", offsetof(struct srun_opt, task_prolog),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "test_only", offsetof(struct srun_opt, test_only),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "unbuffered", offsetof(struct srun_opt, unbuffered),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "user_managed_io", offsetof(struct srun_opt, user_managed_io),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "account", offsetof(struct slurm_options, account),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "acctg_freq", offsetof(struct slurm_options, acctg_freq),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "begin", offsetof(struct slurm_options, begin), cli_lua_push_time_t,
		 cli_lua_set_time_t, NULL },
	{ "blrtsimage", offsetof(struct slurm_options, blrtsimage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "c_constraints", offsetof(struct slurm_options, c_constraints),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "clusters", offsetof(struct slurm_options, clusters),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "comment", offsetof(struct slurm_options, comment),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "constraints", offsetof(struct slurm_options, constraints),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "contiguous", offsetof(struct slurm_options, contiguous),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "core_spec", offsetof(struct slurm_options, core_spec),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "cores_per_socket", offsetof(struct slurm_options,
		 cores_per_socket), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "cpu_freq_gov", offsetof(struct slurm_options, cpu_freq_gov),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "cpu_freq_max", offsetof(struct slurm_options, cpu_freq_max),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "cpu_freq_min", offsetof(struct slurm_options, cpu_freq_min),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "cpus_per_task", offsetof(struct slurm_options, cpus_per_task),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "cpus_set", offsetof(struct slurm_options, cpus_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "cwd", offsetof(struct slurm_options, cwd), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "deadline", offsetof(struct slurm_options, deadline),
		 cli_lua_push_time_t, cli_lua_set_time_t, NULL },
	{ "delay_boot", offsetof(struct slurm_options, delay_boot),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "dependency", offsetof(struct slurm_options, dependency),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "distribution", offsetof(struct slurm_options, distribution),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "egid", offsetof(struct slurm_options, egid), cli_lua_push_gid,
		 NULL, NULL },
	{ "euid", offsetof(struct slurm_options, euid), cli_lua_push_uid,
		 NULL, NULL },
	{ "exc_nodes", offsetof(struct slurm_options, exc_nodes),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "extra", offsetof(struct slurm_options, extra), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "extra_set", offsetof(struct slurm_options, extra_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "get_user_env_mode", offsetof(struct slurm_options,
		 get_user_env_mode), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "get_user_env_time", offsetof(struct slurm_options,
		 get_user_env_time), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "gid", offsetof(struct slurm_options, gid), cli_lua_push_gid, NULL,
		 NULL },
	{ "gres", offsetof(struct slurm_options, gres), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "hint_env", offsetof(struct slurm_options, hint_env),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "hint_set", offsetof(struct slurm_options, hint_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "hold", offsetof(struct slurm_options, hold), cli_lua_push_boolean,
		 cli_lua_set_boolean, NULL },
	{ "immediate", offsetof(struct slurm_options, immediate),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "job_flags", offsetof(struct slurm_options, job_flags),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "job_name", offsetof(struct slurm_options, job_name),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "jobid", offsetof(struct slurm_options, jobid),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "jobid_set", offsetof(struct slurm_options, jobid_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "licenses", offsetof(struct slurm_options, licenses),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "linuximage", offsetof(struct slurm_options, linuximage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mail_type", offsetof(struct slurm_options, mail_type),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "mail_user", offsetof(struct slurm_options, mail_user),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "max_nodes", offsetof(struct slurm_options, max_nodes),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "mcs_label", offsetof(struct slurm_options, mcs_label),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mem_bind", offsetof(struct slurm_options, mem_bind),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mem_bind_type", offsetof(struct slurm_options, mem_bind_type),
		 cli_lua_push_unsigned, cli_lua_set_unsigned, NULL },
	{ "mem_per_cpu", offsetof(struct slurm_options, mem_per_cpu),
		 cli_lua_push_int64_t, cli_lua_set_int64_t, NULL },
	{ "min_nodes", offsetof(struct slurm_options, min_nodes),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "mloaderimage", offsetof(struct slurm_options, mloaderimage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mpi_type", offsetof(struct slurm_options, mpi_type),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "network", offsetof(struct slurm_options, network),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "nice", offsetof(struct slurm_options, nice), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "no_kill", offsetof(struct slurm_options, no_kill),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "no_rotate", offsetof(struct slurm_options, no_rotate),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "nodelist", offsetof(struct slurm_options, nodelist),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "nodes_set", offsetof(struct slurm_options, nodes_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "ntasks", offsetof(struct slurm_options, ntasks), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "ntasks_per_core", offsetof(struct slurm_options, ntasks_per_core),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ntasks_per_core_set", offsetof(struct slurm_options,
		 ntasks_per_core_set), cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "ntasks_per_node", offsetof(struct slurm_options, ntasks_per_node),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ntasks_per_socket", offsetof(struct slurm_options,
		 ntasks_per_socket), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ntasks_set", offsetof(struct slurm_options, ntasks_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "overcommit", offsetof(struct slurm_options, overcommit),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "partition", offsetof(struct slurm_options, partition),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "plane_size", offsetof(struct slurm_options, plane_size),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "pn_min_cpus", offsetof(struct slurm_options, pn_min_cpus),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "pn_min_memory", offsetof(struct slurm_options, pn_min_memory),
		 cli_lua_push_int64_t, cli_lua_set_int64_t, NULL },
	{ "pn_min_tmp_disk", offsetof(struct slurm_options, pn_min_tmp_disk),
		 cli_lua_push_long, cli_lua_set_long, NULL },
	{ "power_flags", offsetof(struct slurm_options, power_flags),
		 cli_lua_push_uint8_t, cli_lua_set_uint8_t, NULL },
	{ "priority", offsetof(struct slurm_options, priority),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "profile", offsetof(struct slurm_options, profile),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "progname", offsetof(struct slurm_options, progname),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "qos", offsetof(struct slurm_options, qos), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "quiet", offsetof(struct slurm_options, quiet), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "ramdiskimage", offsetof(struct slurm_options, ramdiskimage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "reboot", offsetof(struct slurm_options, reboot),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "req_switch", offsetof(struct slurm_options, req_switch),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "reservation", offsetof(struct slurm_options, reservation),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "shared", offsetof(struct slurm_options, shared),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "sockets_per_node", offsetof(struct slurm_options,
		 sockets_per_node), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "spank_job_env", offsetof(struct slurm_options, spank_job_env),
		 cli_lua_stringarray, NULL, "spank_job_env_size" },
	{ "spank_job_env_size", offsetof(struct slurm_options,
		 spank_job_env_size), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "threads_per_core", offsetof(struct slurm_options,
		 threads_per_core), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "threads_per_core_set", offsetof(struct slurm_options,
		 threads_per_core_set), cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "time_limit", offsetof(struct slurm_options, time_limit),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "time_limit_str", offsetof(struct slurm_options, time_limit_str),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "time_min", offsetof(struct slurm_options, time_min),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "time_min_str", offsetof(struct slurm_options, time_min_str),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "uid", offsetof(struct slurm_options, uid), cli_lua_push_uid, NULL,
		 NULL },
	{ "user", offsetof(struct slurm_options, user), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "verbose", offsetof(struct slurm_options, verbose),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "wait4switch", offsetof(struct slurm_options, wait4switch),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "warn_flags", offsetof(struct slurm_options, warn_flags),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "warn_signal", offsetof(struct slurm_options, warn_signal),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "warn_time", offsetof(struct slurm_options, warn_time),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "wckey", offsetof(struct slurm_options, wckey), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "x11", offsetof(struct slurm_options, x11), cli_lua_push_uint16_t,
		 cli_lua_set_uint16_t, NULL },
	{ "x11_magic_cookie", offsetof(struct slurm_options,
		 x11_magic_cookie), cli_lua_push_string, cli_lua_set_string, NULL },
	{ "x11_target_port", offsetof(struct slurm_options, x11_target_port),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ NULL, 0, NULL, NULL, NULL }
};
cli_lua_option_t sbatch_opt_li[] = {
	{ "array_inx", offsetof(struct sbatch_opt, array_inx),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "burst_buffer_file", offsetof(struct sbatch_opt, burst_buffer_file),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "ckpt_dir", offsetof(struct sbatch_opt, ckpt_dir),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "ckpt_interval", offsetof(struct sbatch_opt, ckpt_interval),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ckpt_interval_str", offsetof(struct sbatch_opt, ckpt_interval_str),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "efname", offsetof(struct sbatch_opt, efname), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "export_env", offsetof(struct sbatch_opt, export_env),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "export_file", offsetof(struct sbatch_opt, export_file),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "ifname", offsetof(struct sbatch_opt, ifname), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "mincores", offsetof(struct sbatch_opt, mincores), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "minsockets", offsetof(struct sbatch_opt, minsockets),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "minthreads", offsetof(struct sbatch_opt, minthreads),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ofname", offsetof(struct sbatch_opt, ofname), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "open_mode", offsetof(struct sbatch_opt, open_mode),
		 cli_lua_push_uint8_t, cli_lua_set_uint8_t, NULL },
	{ "parsable", offsetof(struct sbatch_opt, parsable),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "propagate", offsetof(struct sbatch_opt, propagate),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "requeue", offsetof(struct sbatch_opt, requeue), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "script_argc", offsetof(struct sbatch_opt, script_argc),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "script_argv", offsetof(struct sbatch_opt, script_argv),
		 cli_lua_stringarray, NULL, "script_argc" },
	{ "test_only", offsetof(struct sbatch_opt, test_only),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "umask", offsetof(struct sbatch_opt, umask), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "wait", offsetof(struct sbatch_opt, wait), cli_lua_push_boolean,
		 cli_lua_set_boolean, NULL },
	{ "wait_all_nodes", offsetof(struct sbatch_opt, wait_all_nodes),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "wrap", offsetof(struct sbatch_opt, wrap), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "account", offsetof(struct slurm_options, account),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "acctg_freq", offsetof(struct slurm_options, acctg_freq),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "begin", offsetof(struct slurm_options, begin), cli_lua_push_time_t,
		 cli_lua_set_time_t, NULL },
	{ "blrtsimage", offsetof(struct slurm_options, blrtsimage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "c_constraints", offsetof(struct slurm_options, c_constraints),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "clusters", offsetof(struct slurm_options, clusters),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "comment", offsetof(struct slurm_options, comment),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "constraints", offsetof(struct slurm_options, constraints),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "contiguous", offsetof(struct slurm_options, contiguous),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "core_spec", offsetof(struct slurm_options, core_spec),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "cores_per_socket", offsetof(struct slurm_options,
		 cores_per_socket), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "cpu_freq_gov", offsetof(struct slurm_options, cpu_freq_gov),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "cpu_freq_max", offsetof(struct slurm_options, cpu_freq_max),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "cpu_freq_min", offsetof(struct slurm_options, cpu_freq_min),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "cpus_per_task", offsetof(struct slurm_options, cpus_per_task),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "cpus_set", offsetof(struct slurm_options, cpus_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "cwd", offsetof(struct slurm_options, cwd), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "deadline", offsetof(struct slurm_options, deadline),
		 cli_lua_push_time_t, cli_lua_set_time_t, NULL },
	{ "delay_boot", offsetof(struct slurm_options, delay_boot),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "dependency", offsetof(struct slurm_options, dependency),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "distribution", offsetof(struct slurm_options, distribution),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "egid", offsetof(struct slurm_options, egid), cli_lua_push_gid,
		 NULL, NULL },
	{ "euid", offsetof(struct slurm_options, euid), cli_lua_push_uid,
		 NULL, NULL },
	{ "exc_nodes", offsetof(struct slurm_options, exc_nodes),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "extra", offsetof(struct slurm_options, extra), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "extra_set", offsetof(struct slurm_options, extra_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "get_user_env_mode", offsetof(struct slurm_options,
		 get_user_env_mode), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "get_user_env_time", offsetof(struct slurm_options,
		 get_user_env_time), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "gid", offsetof(struct slurm_options, gid), cli_lua_push_gid, NULL,
		 NULL },
	{ "gres", offsetof(struct slurm_options, gres), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "hint_env", offsetof(struct slurm_options, hint_env),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "hint_set", offsetof(struct slurm_options, hint_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "hold", offsetof(struct slurm_options, hold), cli_lua_push_boolean,
		 cli_lua_set_boolean, NULL },
	{ "immediate", offsetof(struct slurm_options, immediate),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "job_flags", offsetof(struct slurm_options, job_flags),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "job_name", offsetof(struct slurm_options, job_name),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "jobid", offsetof(struct slurm_options, jobid),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "jobid_set", offsetof(struct slurm_options, jobid_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "licenses", offsetof(struct slurm_options, licenses),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "linuximage", offsetof(struct slurm_options, linuximage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mail_type", offsetof(struct slurm_options, mail_type),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "mail_user", offsetof(struct slurm_options, mail_user),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "max_nodes", offsetof(struct slurm_options, max_nodes),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "mcs_label", offsetof(struct slurm_options, mcs_label),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mem_bind", offsetof(struct slurm_options, mem_bind),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mem_bind_type", offsetof(struct slurm_options, mem_bind_type),
		 cli_lua_push_unsigned, cli_lua_set_unsigned, NULL },
	{ "mem_per_cpu", offsetof(struct slurm_options, mem_per_cpu),
		 cli_lua_push_int64_t, cli_lua_set_int64_t, NULL },
	{ "min_nodes", offsetof(struct slurm_options, min_nodes),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "mloaderimage", offsetof(struct slurm_options, mloaderimage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mpi_type", offsetof(struct slurm_options, mpi_type),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "network", offsetof(struct slurm_options, network),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "nice", offsetof(struct slurm_options, nice), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "no_kill", offsetof(struct slurm_options, no_kill),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "no_rotate", offsetof(struct slurm_options, no_rotate),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "nodelist", offsetof(struct slurm_options, nodelist),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "nodes_set", offsetof(struct slurm_options, nodes_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "ntasks", offsetof(struct slurm_options, ntasks), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "ntasks_per_core", offsetof(struct slurm_options, ntasks_per_core),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ntasks_per_core_set", offsetof(struct slurm_options,
		 ntasks_per_core_set), cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "ntasks_per_node", offsetof(struct slurm_options, ntasks_per_node),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ntasks_per_socket", offsetof(struct slurm_options,
		 ntasks_per_socket), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ntasks_set", offsetof(struct slurm_options, ntasks_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "overcommit", offsetof(struct slurm_options, overcommit),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "partition", offsetof(struct slurm_options, partition),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "plane_size", offsetof(struct slurm_options, plane_size),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "pn_min_cpus", offsetof(struct slurm_options, pn_min_cpus),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "pn_min_memory", offsetof(struct slurm_options, pn_min_memory),
		 cli_lua_push_int64_t, cli_lua_set_int64_t, NULL },
	{ "pn_min_tmp_disk", offsetof(struct slurm_options, pn_min_tmp_disk),
		 cli_lua_push_long, cli_lua_set_long, NULL },
	{ "power_flags", offsetof(struct slurm_options, power_flags),
		 cli_lua_push_uint8_t, cli_lua_set_uint8_t, NULL },
	{ "priority", offsetof(struct slurm_options, priority),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "profile", offsetof(struct slurm_options, profile),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "progname", offsetof(struct slurm_options, progname),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "qos", offsetof(struct slurm_options, qos), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "quiet", offsetof(struct slurm_options, quiet), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "ramdiskimage", offsetof(struct slurm_options, ramdiskimage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "reboot", offsetof(struct slurm_options, reboot),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "req_switch", offsetof(struct slurm_options, req_switch),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "reservation", offsetof(struct slurm_options, reservation),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "shared", offsetof(struct slurm_options, shared),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "sockets_per_node", offsetof(struct slurm_options,
		 sockets_per_node), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "spank_job_env", offsetof(struct slurm_options, spank_job_env),
		 cli_lua_stringarray, NULL, "spank_job_env_size" },
	{ "spank_job_env_size", offsetof(struct slurm_options,
		 spank_job_env_size), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "threads_per_core", offsetof(struct slurm_options,
		 threads_per_core), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "threads_per_core_set", offsetof(struct slurm_options,
		 threads_per_core_set), cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "time_limit", offsetof(struct slurm_options, time_limit),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "time_limit_str", offsetof(struct slurm_options, time_limit_str),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "time_min", offsetof(struct slurm_options, time_min),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "time_min_str", offsetof(struct slurm_options, time_min_str),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "uid", offsetof(struct slurm_options, uid), cli_lua_push_uid, NULL,
		 NULL },
	{ "user", offsetof(struct slurm_options, user), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "verbose", offsetof(struct slurm_options, verbose),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "wait4switch", offsetof(struct slurm_options, wait4switch),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "warn_flags", offsetof(struct slurm_options, warn_flags),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "warn_signal", offsetof(struct slurm_options, warn_signal),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "warn_time", offsetof(struct slurm_options, warn_time),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "wckey", offsetof(struct slurm_options, wckey), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "x11", offsetof(struct slurm_options, x11), cli_lua_push_uint16_t,
		 cli_lua_set_uint16_t, NULL },
	{ "x11_magic_cookie", offsetof(struct slurm_options,
		 x11_magic_cookie), cli_lua_push_string, cli_lua_set_string, NULL },
	{ "x11_target_port", offsetof(struct slurm_options, x11_target_port),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ NULL, 0, NULL, NULL, NULL }
};
cli_lua_option_t bcast_parameters_li[] = {
	{ "block_size", offsetof(struct bcast_parameters, block_size),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "compress", offsetof(struct bcast_parameters, compress),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "dst_fname", offsetof(struct bcast_parameters, dst_fname),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "fanout", offsetof(struct bcast_parameters, fanout),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "force", offsetof(struct bcast_parameters, force),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "job_id", offsetof(struct bcast_parameters, job_id),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "pack_job_offset", offsetof(struct bcast_parameters,
		 pack_job_offset), cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "preserve", offsetof(struct bcast_parameters, preserve),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "src_fname", offsetof(struct bcast_parameters, src_fname),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "step_id", offsetof(struct bcast_parameters, step_id),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "timeout", offsetof(struct bcast_parameters, timeout),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "verbose", offsetof(struct bcast_parameters, verbose),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ NULL, 0, NULL, NULL, NULL }
};
cli_lua_option_t slurm_options_li[] = {
	{ "account", offsetof(struct slurm_options, account),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "acctg_freq", offsetof(struct slurm_options, acctg_freq),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "begin", offsetof(struct slurm_options, begin), cli_lua_push_time_t,
		 cli_lua_set_time_t, NULL },
	{ "blrtsimage", offsetof(struct slurm_options, blrtsimage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "c_constraints", offsetof(struct slurm_options, c_constraints),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "clusters", offsetof(struct slurm_options, clusters),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "comment", offsetof(struct slurm_options, comment),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "constraints", offsetof(struct slurm_options, constraints),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "contiguous", offsetof(struct slurm_options, contiguous),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "core_spec", offsetof(struct slurm_options, core_spec),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "cores_per_socket", offsetof(struct slurm_options,
		 cores_per_socket), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "cpu_freq_gov", offsetof(struct slurm_options, cpu_freq_gov),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "cpu_freq_max", offsetof(struct slurm_options, cpu_freq_max),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "cpu_freq_min", offsetof(struct slurm_options, cpu_freq_min),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "cpus_per_task", offsetof(struct slurm_options, cpus_per_task),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "cpus_set", offsetof(struct slurm_options, cpus_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "cwd", offsetof(struct slurm_options, cwd), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "deadline", offsetof(struct slurm_options, deadline),
		 cli_lua_push_time_t, cli_lua_set_time_t, NULL },
	{ "delay_boot", offsetof(struct slurm_options, delay_boot),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "dependency", offsetof(struct slurm_options, dependency),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "distribution", offsetof(struct slurm_options, distribution),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "egid", offsetof(struct slurm_options, egid), cli_lua_push_gid,
		 NULL, NULL },
	{ "euid", offsetof(struct slurm_options, euid), cli_lua_push_uid,
		 NULL, NULL },
	{ "exc_nodes", offsetof(struct slurm_options, exc_nodes),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "extra", offsetof(struct slurm_options, extra), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "extra_set", offsetof(struct slurm_options, extra_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "get_user_env_mode", offsetof(struct slurm_options,
		 get_user_env_mode), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "get_user_env_time", offsetof(struct slurm_options,
		 get_user_env_time), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "gid", offsetof(struct slurm_options, gid), cli_lua_push_gid, NULL,
		 NULL },
	{ "gres", offsetof(struct slurm_options, gres), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "hint_env", offsetof(struct slurm_options, hint_env),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "hint_set", offsetof(struct slurm_options, hint_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "hold", offsetof(struct slurm_options, hold), cli_lua_push_boolean,
		 cli_lua_set_boolean, NULL },
	{ "immediate", offsetof(struct slurm_options, immediate),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "job_flags", offsetof(struct slurm_options, job_flags),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "job_name", offsetof(struct slurm_options, job_name),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "jobid", offsetof(struct slurm_options, jobid),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "jobid_set", offsetof(struct slurm_options, jobid_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "licenses", offsetof(struct slurm_options, licenses),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "linuximage", offsetof(struct slurm_options, linuximage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mail_type", offsetof(struct slurm_options, mail_type),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "mail_user", offsetof(struct slurm_options, mail_user),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "max_nodes", offsetof(struct slurm_options, max_nodes),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "mcs_label", offsetof(struct slurm_options, mcs_label),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mem_bind", offsetof(struct slurm_options, mem_bind),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mem_bind_type", offsetof(struct slurm_options, mem_bind_type),
		 cli_lua_push_unsigned, cli_lua_set_unsigned, NULL },
	{ "mem_per_cpu", offsetof(struct slurm_options, mem_per_cpu),
		 cli_lua_push_int64_t, cli_lua_set_int64_t, NULL },
	{ "min_nodes", offsetof(struct slurm_options, min_nodes),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "mloaderimage", offsetof(struct slurm_options, mloaderimage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mpi_type", offsetof(struct slurm_options, mpi_type),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "network", offsetof(struct slurm_options, network),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "nice", offsetof(struct slurm_options, nice), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "no_kill", offsetof(struct slurm_options, no_kill),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "no_rotate", offsetof(struct slurm_options, no_rotate),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "nodelist", offsetof(struct slurm_options, nodelist),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "nodes_set", offsetof(struct slurm_options, nodes_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "ntasks", offsetof(struct slurm_options, ntasks), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "ntasks_per_core", offsetof(struct slurm_options, ntasks_per_core),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ntasks_per_core_set", offsetof(struct slurm_options,
		 ntasks_per_core_set), cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "ntasks_per_node", offsetof(struct slurm_options, ntasks_per_node),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ntasks_per_socket", offsetof(struct slurm_options,
		 ntasks_per_socket), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ntasks_set", offsetof(struct slurm_options, ntasks_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "overcommit", offsetof(struct slurm_options, overcommit),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "partition", offsetof(struct slurm_options, partition),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "plane_size", offsetof(struct slurm_options, plane_size),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "pn_min_cpus", offsetof(struct slurm_options, pn_min_cpus),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "pn_min_memory", offsetof(struct slurm_options, pn_min_memory),
		 cli_lua_push_int64_t, cli_lua_set_int64_t, NULL },
	{ "pn_min_tmp_disk", offsetof(struct slurm_options, pn_min_tmp_disk),
		 cli_lua_push_long, cli_lua_set_long, NULL },
	{ "power_flags", offsetof(struct slurm_options, power_flags),
		 cli_lua_push_uint8_t, cli_lua_set_uint8_t, NULL },
	{ "priority", offsetof(struct slurm_options, priority),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "profile", offsetof(struct slurm_options, profile),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "progname", offsetof(struct slurm_options, progname),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "qos", offsetof(struct slurm_options, qos), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "quiet", offsetof(struct slurm_options, quiet), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "ramdiskimage", offsetof(struct slurm_options, ramdiskimage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "reboot", offsetof(struct slurm_options, reboot),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "req_switch", offsetof(struct slurm_options, req_switch),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "reservation", offsetof(struct slurm_options, reservation),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "shared", offsetof(struct slurm_options, shared),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "sockets_per_node", offsetof(struct slurm_options,
		 sockets_per_node), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "spank_job_env", offsetof(struct slurm_options, spank_job_env),
		 cli_lua_stringarray, NULL, "spank_job_env_size" },
	{ "spank_job_env_size", offsetof(struct slurm_options,
		 spank_job_env_size), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "threads_per_core", offsetof(struct slurm_options,
		 threads_per_core), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "threads_per_core_set", offsetof(struct slurm_options,
		 threads_per_core_set), cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "time_limit", offsetof(struct slurm_options, time_limit),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "time_limit_str", offsetof(struct slurm_options, time_limit_str),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "time_min", offsetof(struct slurm_options, time_min),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "time_min_str", offsetof(struct slurm_options, time_min_str),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "uid", offsetof(struct slurm_options, uid), cli_lua_push_uid, NULL,
		 NULL },
	{ "user", offsetof(struct slurm_options, user), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "verbose", offsetof(struct slurm_options, verbose),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "wait4switch", offsetof(struct slurm_options, wait4switch),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "warn_flags", offsetof(struct slurm_options, warn_flags),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "warn_signal", offsetof(struct slurm_options, warn_signal),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "warn_time", offsetof(struct slurm_options, warn_time),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "wckey", offsetof(struct slurm_options, wckey), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "x11", offsetof(struct slurm_options, x11), cli_lua_push_uint16_t,
		 cli_lua_set_uint16_t, NULL },
	{ "x11_magic_cookie", offsetof(struct slurm_options,
		 x11_magic_cookie), cli_lua_push_string, cli_lua_set_string, NULL },
	{ "x11_target_port", offsetof(struct slurm_options, x11_target_port),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ NULL, 0, NULL, NULL, NULL }
};
cli_lua_option_t salloc_opt_li[] = {
	{ "burst_buffer", offsetof(struct salloc_opt, burst_buffer),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "default_job_name", offsetof(struct salloc_opt, default_job_name),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "kill_command_signal", offsetof(struct salloc_opt,
		 kill_command_signal), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "kill_command_signal_set", offsetof(struct salloc_opt,
		 kill_command_signal_set), cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "no_shell", offsetof(struct salloc_opt, no_shell),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "wait_all_nodes", offsetof(struct salloc_opt, wait_all_nodes),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "account", offsetof(struct slurm_options, account),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "acctg_freq", offsetof(struct slurm_options, acctg_freq),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "begin", offsetof(struct slurm_options, begin), cli_lua_push_time_t,
		 cli_lua_set_time_t, NULL },
	{ "blrtsimage", offsetof(struct slurm_options, blrtsimage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "c_constraints", offsetof(struct slurm_options, c_constraints),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "clusters", offsetof(struct slurm_options, clusters),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "comment", offsetof(struct slurm_options, comment),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "constraints", offsetof(struct slurm_options, constraints),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "contiguous", offsetof(struct slurm_options, contiguous),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "core_spec", offsetof(struct slurm_options, core_spec),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "cores_per_socket", offsetof(struct slurm_options,
		 cores_per_socket), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "cpu_freq_gov", offsetof(struct slurm_options, cpu_freq_gov),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "cpu_freq_max", offsetof(struct slurm_options, cpu_freq_max),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "cpu_freq_min", offsetof(struct slurm_options, cpu_freq_min),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "cpus_per_task", offsetof(struct slurm_options, cpus_per_task),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "cpus_set", offsetof(struct slurm_options, cpus_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "cwd", offsetof(struct slurm_options, cwd), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "deadline", offsetof(struct slurm_options, deadline),
		 cli_lua_push_time_t, cli_lua_set_time_t, NULL },
	{ "delay_boot", offsetof(struct slurm_options, delay_boot),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "dependency", offsetof(struct slurm_options, dependency),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "distribution", offsetof(struct slurm_options, distribution),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "egid", offsetof(struct slurm_options, egid), cli_lua_push_gid,
		 NULL, NULL },
	{ "euid", offsetof(struct slurm_options, euid), cli_lua_push_uid,
		 NULL, NULL },
	{ "exc_nodes", offsetof(struct slurm_options, exc_nodes),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "extra", offsetof(struct slurm_options, extra), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "extra_set", offsetof(struct slurm_options, extra_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "get_user_env_mode", offsetof(struct slurm_options,
		 get_user_env_mode), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "get_user_env_time", offsetof(struct slurm_options,
		 get_user_env_time), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "gid", offsetof(struct slurm_options, gid), cli_lua_push_gid, NULL,
		 NULL },
	{ "gres", offsetof(struct slurm_options, gres), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "hint_env", offsetof(struct slurm_options, hint_env),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "hint_set", offsetof(struct slurm_options, hint_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "hold", offsetof(struct slurm_options, hold), cli_lua_push_boolean,
		 cli_lua_set_boolean, NULL },
	{ "immediate", offsetof(struct slurm_options, immediate),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "job_flags", offsetof(struct slurm_options, job_flags),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "job_name", offsetof(struct slurm_options, job_name),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "jobid", offsetof(struct slurm_options, jobid),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "jobid_set", offsetof(struct slurm_options, jobid_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "licenses", offsetof(struct slurm_options, licenses),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "linuximage", offsetof(struct slurm_options, linuximage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mail_type", offsetof(struct slurm_options, mail_type),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "mail_user", offsetof(struct slurm_options, mail_user),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "max_nodes", offsetof(struct slurm_options, max_nodes),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "mcs_label", offsetof(struct slurm_options, mcs_label),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mem_bind", offsetof(struct slurm_options, mem_bind),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mem_bind_type", offsetof(struct slurm_options, mem_bind_type),
		 cli_lua_push_unsigned, cli_lua_set_unsigned, NULL },
	{ "mem_per_cpu", offsetof(struct slurm_options, mem_per_cpu),
		 cli_lua_push_int64_t, cli_lua_set_int64_t, NULL },
	{ "min_nodes", offsetof(struct slurm_options, min_nodes),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "mloaderimage", offsetof(struct slurm_options, mloaderimage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "mpi_type", offsetof(struct slurm_options, mpi_type),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "network", offsetof(struct slurm_options, network),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "nice", offsetof(struct slurm_options, nice), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "no_kill", offsetof(struct slurm_options, no_kill),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "no_rotate", offsetof(struct slurm_options, no_rotate),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "nodelist", offsetof(struct slurm_options, nodelist),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "nodes_set", offsetof(struct slurm_options, nodes_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "ntasks", offsetof(struct slurm_options, ntasks), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "ntasks_per_core", offsetof(struct slurm_options, ntasks_per_core),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ntasks_per_core_set", offsetof(struct slurm_options,
		 ntasks_per_core_set), cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "ntasks_per_node", offsetof(struct slurm_options, ntasks_per_node),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ntasks_per_socket", offsetof(struct slurm_options,
		 ntasks_per_socket), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "ntasks_set", offsetof(struct slurm_options, ntasks_set),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "overcommit", offsetof(struct slurm_options, overcommit),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "partition", offsetof(struct slurm_options, partition),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "plane_size", offsetof(struct slurm_options, plane_size),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "pn_min_cpus", offsetof(struct slurm_options, pn_min_cpus),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "pn_min_memory", offsetof(struct slurm_options, pn_min_memory),
		 cli_lua_push_int64_t, cli_lua_set_int64_t, NULL },
	{ "pn_min_tmp_disk", offsetof(struct slurm_options, pn_min_tmp_disk),
		 cli_lua_push_long, cli_lua_set_long, NULL },
	{ "power_flags", offsetof(struct slurm_options, power_flags),
		 cli_lua_push_uint8_t, cli_lua_set_uint8_t, NULL },
	{ "priority", offsetof(struct slurm_options, priority),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "profile", offsetof(struct slurm_options, profile),
		 cli_lua_push_uint32_t, cli_lua_set_uint32_t, NULL },
	{ "progname", offsetof(struct slurm_options, progname),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "qos", offsetof(struct slurm_options, qos), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "quiet", offsetof(struct slurm_options, quiet), cli_lua_push_int,
		 cli_lua_set_int, NULL },
	{ "ramdiskimage", offsetof(struct slurm_options, ramdiskimage),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "reboot", offsetof(struct slurm_options, reboot),
		 cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "req_switch", offsetof(struct slurm_options, req_switch),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "reservation", offsetof(struct slurm_options, reservation),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "shared", offsetof(struct slurm_options, shared),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "sockets_per_node", offsetof(struct slurm_options,
		 sockets_per_node), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "spank_job_env", offsetof(struct slurm_options, spank_job_env),
		 cli_lua_stringarray, NULL, "spank_job_env_size" },
	{ "spank_job_env_size", offsetof(struct slurm_options,
		 spank_job_env_size), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "threads_per_core", offsetof(struct slurm_options,
		 threads_per_core), cli_lua_push_int, cli_lua_set_int, NULL },
	{ "threads_per_core_set", offsetof(struct slurm_options,
		 threads_per_core_set), cli_lua_push_boolean, cli_lua_set_boolean, NULL },
	{ "time_limit", offsetof(struct slurm_options, time_limit),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "time_limit_str", offsetof(struct slurm_options, time_limit_str),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "time_min", offsetof(struct slurm_options, time_min),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "time_min_str", offsetof(struct slurm_options, time_min_str),
		 cli_lua_push_string, cli_lua_set_string, NULL },
	{ "uid", offsetof(struct slurm_options, uid), cli_lua_push_uid, NULL,
		 NULL },
	{ "user", offsetof(struct slurm_options, user), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "verbose", offsetof(struct slurm_options, verbose),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "wait4switch", offsetof(struct slurm_options, wait4switch),
		 cli_lua_push_int, cli_lua_set_int, NULL },
	{ "warn_flags", offsetof(struct slurm_options, warn_flags),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "warn_signal", offsetof(struct slurm_options, warn_signal),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "warn_time", offsetof(struct slurm_options, warn_time),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ "wckey", offsetof(struct slurm_options, wckey), cli_lua_push_string,
		 cli_lua_set_string, NULL },
	{ "x11", offsetof(struct slurm_options, x11), cli_lua_push_uint16_t,
		 cli_lua_set_uint16_t, NULL },
	{ "x11_magic_cookie", offsetof(struct slurm_options,
		 x11_magic_cookie), cli_lua_push_string, cli_lua_set_string, NULL },
	{ "x11_target_port", offsetof(struct slurm_options, x11_target_port),
		 cli_lua_push_uint16_t, cli_lua_set_uint16_t, NULL },
	{ NULL, 0, NULL, NULL, NULL }
};
